version: '3.5'

services:
  streetparty_api:
    image: streetparty_api
    container_name: streetparty_api
    build: .
    restart: always
    ports:
      - "9080:9080"
    volumes:
      - ".:/app"
  streetparty_nginx:
    image: nginx:latest
    container_name: streetparty_nginx
    depends_on:
      - streetparty_api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./bin/wait-for-it.sh:/bin/wait-for-it"
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/log:/var/nginx/log"
    command: wait-for-it streetparty_api:9080 -t 0 -- nginx -g 'daemon off;'